[target.thumbv7em-none-eabi]
runner = 'arm-none-eabi-gdb -q -x openocd.gdb'
runflags = [
	"-C", "link-arg=-Tlink.x",
]

[target.thumbv6m-none-eabi]
runner = 'arm-none-eabi-gdb -q -x openocd.gdb'
rustflags = [
	"-C", "link-arg=-Tlink.x",
]

[build]
#target = "thumbv7em-none-eabi" #cortex m4
target = "thumbv6m-none-eabi" #cortex m0+